### ISSUE TITLE
Doesn't hide Anonymous View icon/link

### ISSUE THREAD

**Issue by tuurep** [DrHaid/startpage-result-favicons#2]
From the Mozilla Addons page's screenshot I see the Anonymous View used to be an icon next to the webpage address which is then replaced as the favicon by this addon.

However now it looks like this:

![image](https://github.com/user-attachments/assets/9c6b7011-319f-4feb-bb93-6dc5522fb4c3)

I'm wondering if there's some outdated code here, and whether this has any relation to #1 

Personally I hate the "Visit in Anonymous View" -link spam so I'm looking for a way to entirely hide them, while still having the ability to use the Anonymous View some other way, similarly to how this addon was intended to work in the past.

**Comment by DrHaid** [comment]
Yeah, Startpage moved the "Anonymous View" button a while ago. It used to be where the favicons are now, so out of convenience I just replaced that icon with the favicon for that result keeping the anonymous link.
That's why that "feature" existed 😅

Didn't feel right to actively get rid of the new button now as this add-on is supposed to only add favicons.
But I might add that again as an optional setting (and actually update the screenshots and add-on description 👀).

**Comment by tuurep** [comment]
Ah, good to know that you're aware of it. Thanks!

I'd be in favor of favicon-as-Anonymous-View option, although do agree it's a bit of an odd responsibility for this plugin :smile: but I would use it, tbh..

I'll take a good look at the other issue and try with a clean firefox profile too but I'll have to do that tomorrow because I'm going to sleep :)

**Comment by DrHaid** [comment]
I just released v1.0.0 that added the option to hide the Anonymous View link. Behavior will be like before, so the icons can be used to enter Anonymous View.
Let me know there's any problems with the new version 😅

**Comment by tuurep** [comment]
Thanks, I tried it out and works great

Great settings popup

First time I heard about [twenty](https://github.com/twentyhq/favicon), looks neat
