### ISSUE TITLE
FEATURE REQUEST: Mobile Support

### ISSUE THREAD

**Issue by BredMan0** [DrHaid/startpage-result-favicons#9]
Hello. I love the extension. I have the extension installed on both firefox on android and on desktop, but it only works on the desktop version of Startpage. This seems to be due to the fact that the desktop and mobile version of Startpage are different. It would be awesome to have this extension support mobile, too.

**Comment by DrHaid** [comment]
I already thought about getting it to mobile because I also use Firefox on Android, so now I definitely will.
The extension is not in the official mobile add-on store (because it's not officially supported yet), so I assume you installed the desktop version 🤔
But yes, I guess the mobile Startpage is different, and that's why it doesn't work.

**Comment by DrHaid** [comment]
Alrighty, it's available it in the Firefox add-on store on mobile now 👌

**Comment by tuurep** [comment]
Thanks, it works!

Sometimes icons are quite blurry, could it be that they're quite a bit larger on mobile and it scales up icons that are too tiny?

The ones from source "Twenty" look most appropriate on mobile, but it looks like it has the highest chance of missing an icon.

**Comment by DrHaid** [comment]
Yeah, looks like the Twenty icons generally have the highest resolution while the others are smaller. Not much I can do there unfortunately 😕

**Comment by BredMan0** [comment]
> Alrighty, it's available it in the Firefox add-on store on mobile now 👌

Lovely, it works wonderfully. Great job!
